name: sms_detector
description: A flutter plugin for receiving incoming sms in android. Currently supports on only Android.
version: 0.0.1
author: Md. Abdur Rouf <developer.rouf69nb@gmail.com>
homepage: https://github.com/developer-rouf69nb/sms_detector

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.codepoka.sms_detector
    pluginClass: SmsDetectorPlugin

